services:
  frontend:
    build: ./mern/frontend
    environment:
      REACT_APP_API_URL: http://backend:5050
    ports:
      - "5173:5173"
    image: yashpatil16/mern-frontend:latest
    networks:
      - mern
    
   

  backend:
    build: ./mern/backend
    environment:
      MONGO_URI: mongodb://mongo:27017/employees
      
    ports:
      - "5050:5050"
    image: yashpatil16/mern-backend:latest
    networks:
      - mern
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      - mongo-data:/data/db

networks:
  mern:
    driver: bridge

volumes:
  mongo-data:
    driver: local
 
 
    