def gv
pipeline{
    agent any
    stages{
        stage("Initialize groovy script"){
           steps{
               script{
                   gv = load "/First-DockerImage/script.groovy"
               }
           } 
           
        }
        stage("Build Image"){
            steps{
                script{
                    gv.buildImage()
                }
            }

        }
        
    }
    
}
